---
services:
  redis-1:
    image: bitnami/redis:6.2.13
    init: true
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      jedis:
        ipv4_address: 172.20.1.1

  redis-2:
    image: bitnami/redis:6.2.13
    init: true
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=172.20.1.1
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      jedis:
        ipv4_address: 172.20.1.2

  redis-sentinel-1:
    image: bitnami/redis-sentinel:6.2.13
    init: true
    environment:
      - REDIS_MASTER_HOST=172.20.1.1
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=1000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=2000
      - REDIS_SENTINEL_QUORUM=2
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      jedis:
        ipv4_address: 172.20.2.1

  redis-sentinel-2:
    image: bitnami/redis-sentinel:6.2.13
    init: true
    environment:
      - REDIS_MASTER_HOST=172.20.1.1
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=1000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=2000
      - REDIS_SENTINEL_QUORUM=2
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      jedis:
        ipv4_address: 172.20.2.2

  redis-sentinel-3:
    image: bitnami/redis-sentinel:6.2.13
    init: true
    environment:
      - REDIS_MASTER_HOST=172.20.1.1
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=1000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=2000
      - REDIS_SENTINEL_QUORUM=2
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      jedis:
        ipv4_address: 172.20.2.3

  devcontainer:
    image: jedis-test:dev
    build:
      context: .devcontainer
    init: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    command: "sleep infinity"
    networks:
      jedis:
        ipv4_address: 172.20.3.1

networks:
  jedis:
    ipam:
      config:
        - subnet: 172.20.0.0/16
