---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jarppe-devcontainer-pvc
  labels:
    devcontainer: "true"
    programmer: jarppe
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: jarppe-devcontainer
  labels:
    app: devcontainer
    devcontainer: "true"
    programmer: jarppe
spec:
  containers:
    - name:  app
      image: jarppe/cljdev:dev
      args:  ["sleep", "infinity"]
      env:
       - name:  GIT_AUTHOR_EMAIL
         value: ${GIT_AUTHOR_EMAIL}
       - name:  GIT_COMMITTER_EMAIL
         value: ${GIT_COMMITTER_EMAIL}
       - name:  KUBE_CONTEXT
         value: ${KUBE_CONTEXT}
       - name:  KUBE_NAMESPACE
         value: ${KUBE_NAMESPACE}
      volumeMounts:
        - name:      persistent-storage
          mountPath: /workspace
          subPath:   workspace
        - name:      persistent-storage
          mountPath: /root/.vscode-server
          subPath:   vscode-cache
      resources:
        requests:
          cpu:    1000m
          memory: 2000Mi          
        limits:
          cpu:    2000m
          memory: 4000Mi
    - name: kube-proxy
      image: bitnami/kubectl:latest
      command:
        - kubectl
      args:
        - proxy
        - '--port'
        - '9000'
      resources:
        requests:
          memory: 800Mi
      volumeMounts:
        - name: kube-api-access
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  serviceAccountName: render-api
  serviceAccount: render-api
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: jarppe-devcontainer-pvc
    - name: kube-api-access
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
