---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jarppe-devcontainer-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: jarppe-devcontainer
  labels:
    app: devcontainer
spec:
  containers:
    - name:  app
      image: 633143897132.dkr.ecr.eu-west-1.amazonaws.com/tools:f80fe61c
      args:  ["sleep", "infinity"]
      env:
       - name:  GIT_AUTHOR_EMAIL
         value: ${GIT_AUTHOR_EMAIL}
       - name:  GIT_COMMITTER_EMAIL
         value: ${GIT_COMMITTER_EMAIL}
       - name:  KUBE_CONTEXT
         value: ${KUBE_CONTEXT}
       - name:  KUBE_NAMESPACE
         value: ${KUBE_NAMESPACE}
      volumeMounts:
        - name:      persistent-storage
          mountPath: /workspace
          subPath:   workspace
        - name:      persistent-storage
          mountPath: /root/.vscode-server
          subPath:   vscode-cache
      resources:
        requests:
          cpu:    1000m
          memory: 2000Mi          
        limits:
          cpu:    2000m
          memory: 4000Mi
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: jarppe-devcontainer-pvc
