---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jarppe-devcontainer-pvc
  labels:
    devcontainer: "true"
    programmer: jarppe
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jarppe-devcontainer-sa
  namespace: review-3789
  labels:
    devcontainer: "true"
    programmer: jarppe

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jarppe-devcontainer-crb
  namespace: review-3789
  labels:
    devcontainer: "true"
    programmer: jarppe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole 
  name: cluster-admin
subjects:
- kind: ServiceAccount 
  namespace: review-3789
  name: jarppe-devcontainer-sa
  
---
apiVersion: v1
kind: Pod
metadata:
  name: jarppe-devcontainer
  namespace: review-3789
  labels:
    devcontainer: "true"
    programmer: jarppe
spec:
  containers:
    - name:  app
      image: jarppe/cljdev:dev
      imagePullPolicy: Always
      args:  ["sleep", "infinity"]
      env:
       - name:  GIT_AUTHOR_EMAIL
         value: ${GIT_AUTHOR_EMAIL}
       - name:  GIT_COMMITTER_EMAIL
         value: ${GIT_COMMITTER_EMAIL}
       - name:  KUBE_CONTEXT
         value: ${KUBE_CONTEXT}
       - name:  KUBE_NAMESPACE
         value: ${KUBE_NAMESPACE}
      volumeMounts:
        - name:      persistent-storage
          subPath:   workspace
          mountPath: /workspace
        - name:      persistent-storage
          subPath:   vscode-cache
          mountPath: /root/.vscode-server
        - name:      ssh-keys
          subPath:   id_ed25519
          mountPath: /root/.ssh/id_ed25519
        - name:      ssh-keys
          subPath:   id_ed25519.pub
          mountPath: /root/.ssh/id_ed25519.pub
      resources:
        requests:
          cpu:    1000m
          memory: 2000Mi          
        limits:
          cpu:    2000m
          memory: 4000Mi
    - name: kube-proxy
      image: bitnami/kubectl:latest
      imagePullPolicy: IfNotPresent
      command:
        - kubectl
      args:
        - proxy
        - '--port'
        - '9000'
      resources:
        requests:
          cpu:    100m
          memory: 200Mi          
        limits:
          cpu:    200m
          memory: 400Mi
      volumeMounts:
        - name: kube-api-access
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      terminationMessagePath: /dev/termination-log
  serviceAccountName: jarppe-devcontainer-sa
  serviceAccount: jarppe-devcontainer-sa
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: jarppe-devcontainer-pvc
    - name: ssh-keys
      secret:
        secretName: jarppe-devcontainer-ssh-secrets
        defaultMode: 256
    - name: kube-api-access
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
